In [1]:
print("Hello Khushi")

Hello Khushi

In [2]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [3]:
import sys
print(sys.executable)

D:\Projects\Spam_classifier_detection\venv\Scripts\python.exe

In [4]:
!pip list

Package                   Version
------------------------- -----------
anyio                     4.14.0
argon2-cffi               25.1.0
argon2-cffi-bindings      25.1.0
arrow                     1.4.0
asttokens                 3.0.1
async-lru                 2.3.0
attrs                     26.1.0
babel                     2.18.0
beautifulsoup4            4.15.0
bleach                    6.4.0
certifi                   2026.6.17
cffi                      2.0.0
charset-normalizer        3.4.7
colorama                  0.4.6
comm                      0.2.3
debugpy                   1.8.21
decorator                 5.3.1
defusedxml                0.7.1
executing                 2.2.1
fastjsonschema            2.21.2
fqdn                      1.5.1
h11                       0.16.0
httpcore                  1.0.9
httpx                     0.28.1
idna                      3.18
ipykernel                 7.3.0
ipython                   9.14.1
ipython_pygments_lexers   1.1.1
isoduration               20.11.0
jedi                      0.20.0
Jinja2                    3.1.6
json5                     0.14.0
jsonpointer               3.1.1
jsonschema                4.26.0
jsonschema-specifications 2025.9.1
jupyter_client            8.9.1
jupyter_core              5.9.1
jupyter-events            0.12.1
jupyter-lsp               2.3.1
jupyter_server            2.20.0
jupyter_server_terminals  0.5.4
jupyterlab                4.5.9
jupyterlab_pygments       0.3.0
jupyterlab_server         2.28.0
lark                      1.3.1
MarkupSafe                3.0.3
matplotlib-inline         0.2.2
mistune                   3.2.1
nbclient                  0.11.0
nbconvert                 7.17.1
nbformat                  5.10.4
nest-asyncio2             1.7.2
notebook                  7.5.7
notebook_shim             0.2.4
packaging                 26.2
pandocfilters             1.5.1
parso                     0.8.7
pip                       25.3
platformdirs              4.10.0
prometheus_client         0.25.0
prompt_toolkit            3.0.52
psutil                    7.2.2
pure_eval                 0.2.3
pycparser                 3.0
Pygments                  2.20.0
python-dateutil           2.9.0.post0
python-json-logger        4.1.0
pywinpty                  3.0.5
PyYAML                    6.0.3
pyzmq                     27.1.0
referencing               0.37.0
requests                  2.34.2
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rfc3987-syntax            1.1.0
rpds-py                   2026.5.1
Send2Trash                2.1.0
setuptools                82.0.1
six                       1.17.0
soupsieve                 2.8.4
stack-data                0.6.3
terminado                 0.18.1
tinycss2                  1.5.1
tornado                   6.5.7
traitlets                 5.15.1
typing_extensions         4.15.0
tzdata                    2026.2
uri-template              1.3.0
urllib3                   2.7.0
wcwidth                   0.8.1
webcolors                 25.10.0
webencodings              0.5.1
websocket-client          1.9.0

In [7]:
import sys
!{sys.executable} -m pip install pandas numpy scikit-learn nltk matplotlib seaborn streamlit joblib

Requirement already satisfied: pandas in d:\projects\spam_classifier_detection\venv\lib\site-packages (3.0.3)
Requirement already satisfied: numpy in d:\projects\spam_classifier_detection\venv\lib\site-packages (2.4.6)
Requirement already satisfied: scikit-learn in d:\projects\spam_classifier_detection\venv\lib\site-packages (1.9.0)
Requirement already satisfied: nltk in d:\projects\spam_classifier_detection\venv\lib\site-packages (3.9.4)
Requirement already satisfied: matplotlib in d:\projects\spam_classifier_detection\venv\lib\site-packages (3.11.0)
Requirement already satisfied: seaborn in d:\projects\spam_classifier_detection\venv\lib\site-packages (0.13.2)
Requirement already satisfied: streamlit in d:\projects\spam_classifier_detection\venv\lib\site-packages (1.58.0)
Requirement already satisfied: joblib in d:\projects\spam_classifier_detection\venv\lib\site-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\projects\spam_classifier_detection\venv\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: scipy>=1.10.0 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: narwhals>=2.0.1 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from scikit-learn) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: click in d:\projects\spam_classifier_detection\venv\lib\site-packages (from nltk) (8.4.1)
Requirement already satisfied: regex>=2021.8.3 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from nltk) (2026.5.9)
Requirement already satisfied: tqdm in d:\projects\spam_classifier_detection\venv\lib\site-packages (from nltk) (4.68.3)
Requirement already satisfied: contourpy>=1.0.1 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=9 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from streamlit) (6.2.1)
Requirement already satisfied: blinker<2,>=1.5.0 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from streamlit) (7.1.4)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from streamlit) (3.1.50)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from streamlit) (0.9.2)
Requirement already satisfied: protobuf<8,>=3.20 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from streamlit) (7.35.1)
Requirement already satisfied: pyarrow>=7.0 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from streamlit) (24.0.0)
Requirement already satisfied: requests<3,>=2.27 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from streamlit) (2.34.2)
Requirement already satisfied: tenacity<10,>=8.1.0 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from streamlit) (4.15.0)
Requirement already satisfied: starlette>=0.40.0 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from streamlit) (1.3.1)
Requirement already satisfied: uvicorn>=0.30.0 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from streamlit) (0.49.0)
Requirement already satisfied: httptools>=0.6.3 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from streamlit) (0.8.0)
Requirement already satisfied: anyio>=4.0.0 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from streamlit) (4.14.0)
Requirement already satisfied: python-multipart>=0.0.10 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets>=12.0.0 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from streamlit) (16.0)
Requirement already satisfied: itsdangerous>=2.1.2 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: colorama in d:\projects\spam_classifier_detection\venv\lib\site-packages (from click->nltk) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from requests<3,>=2.27->streamlit) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from requests<3,>=2.27->streamlit) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from requests<3,>=2.27->streamlit) (2026.6.17)
Requirement already satisfied: MarkupSafe>=2.0 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2026.5.1)
Requirement already satisfied: six>=1.5 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: h11>=0.8 in d:\projects\spam_classifier_detection\venv\lib\site-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
import pandas as pd
import numpy as np

print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

Pandas version: 3.0.3
NumPy version: 2.4.6

In [10]:
import pandas as pd

In [11]:
df = pd.read_csv("../data/spam.csv", encoding ="latin-1")

In [12]:
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [13]:
df.columns

Index(['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='str')

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   str
 1   v2          5572 non-null   str
 2   Unnamed: 2  50 non-null     str
 3   Unnamed: 3  12 non-null     str
 4   Unnamed: 4  6 non-null      str
dtypes: str(5)
memory usage: 677.1 KB

In [15]:
df.shape

(5572, 5)

In [16]:
df.drop(columns=['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], inplace = True)

In [17]:
df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [18]:
df.rename(columns={'v1':'target', 'v2':'message'}, inplace=True)

In [19]:
df.head()

  target                                            message
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [20]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['target'] = encoder.fit_transform(df['target'])

In [21]:
df.head()

   target                                            message
0       0  Go until jurong point, crazy.. Available only ...
1       0                      Ok lar... Joking wif u oni...
2       1  Free entry in 2 a wkly comp to win FA Cup fina...
3       0  U dun say so early hor... U c already then say...
4       0  Nah I don't think he goes to usf, he lives aro...

In [22]:
df.isnull().sum()

target     0
message    0
dtype: int64

In [23]:
df.duplicated().sum()

np.int64(403)

In [24]:
df = df.drop_duplicates(keep='first')

In [26]:
df.shape

(5169, 2)

In [28]:
df['target'].value_counts()

target
0    4516
1     653
Name: count, dtype: int64

In [29]:
df['target'].value_counts(normalize=True) * 100

target
0    87.366996
1    12.633004
Name: proportion, dtype: float64

In [30]:
df['num_characters'] = df['message'].apply(len)

In [31]:
df['num_words'] = df['message'].apply(lambda x: len(x.split()))

In [32]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\asus\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.

True

In [35]:
from nltk.tokenize import sent_tokenize

df['num_sentences'] = df['message'].apply(
    lambda x: len(sent_tokenize(x))
)

LookupError:
**********************************************************************
  Resource 'punkt_tab' not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')

  For more information see: https://www.nltk.org/data.html

  Attempted to load 'tokenizers/punkt_tab/english/'

  Searched in:
    - 'C:\\Users\\asus/nltk_data'
    - 'D:\\Projects\\Spam_classifier_detection\\venv\\nltk_data'
    - 'D:\\Projects\\Spam_classifier_detection\\venv\\share\\nltk_data'
    - 'D:\\Projects\\Spam_classifier_detection\\venv\\lib\\nltk_data'
    - 'C:\\Users\\asus\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

In [36]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\asus\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

In [38]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\asus\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\asus\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [39]:
from nltk.tokenize import sent_tokenize
df['num_sentences'] = df['message'].apply(lambda x: len(sent_tokenize(x)))

In [40]:
df.head()

,target,message,num_characters,num_words,num_sentences
0,0,"Go until jurong point, crazy.. Available only ...",111,20,2
1,0,Ok lar... Joking wif u oni...,29,6,2
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,155,28,2
3,0,U dun say so early hor... U c already then say...,49,11,1
4,0,"Nah I don't think he goes to usf, he lives aro...",61,13,1

In [41]:
import string 
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [42]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\asus\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [43]:
ps = PorterStemmer()

In [44]:
ps.stem("running")

'run'

In [52]:
def transform_text(text):
    #Covert to lowercase
    text = text.lower()

    #Tokenization
    text = nltk.word_tokenize(text)

    y = []

    #keep only alphanumeric words
    for i in text:
        if i.isalnum():
            y.append(i)

    text = y[:]
    y.clear()

    #Remove stopwords and punctuation
    for i in text:
        if i not in stopwords.words('english') and i not in string.punctuation:
            y.append(i)

    text = y[:]
    y.clear()

    #Stemming
    for i in text:
        y.append(ps.stem(i))

    return " ".join(y)

In [53]:
transform_text("Hello!!! How are you doing today?")

'hello today'

In [54]:
df['transformed_text'] = df['message'].apply(transform_text)

In [56]:
df[['message', 'transformed_text']].head()

,message,transformed_text
0,"Go until jurong point, crazy.. Available only ...",go jurong point crazi avail bugi n great world...
1,Ok lar... Joking wif u oni...,ok lar joke wif u oni
2,Free entry in 2 a wkly comp to win FA Cup fina...,free entri 2 wkli comp win fa cup final tkt 21...
3,U dun say so early hor... U c already then say...,u dun say earli hor u c alreadi say
4,"Nah I don't think he goes to usf, he lives aro...",nah think goe usf live around though

In [57]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [58]:
tfidf = TfidfVectorizer(max_features=3000)

In [59]:
X = tfidf.fit_transform(df['transformed_text']).toarray()

In [60]:
y = df['target'].values

In [62]:
X.shape

(5169, 3000)

In [63]:
from sklearn.model_selection import train_test_split

In [64]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [65]:
from sklearn.naive_bayes import MultinomialNB

In [67]:
model = MultinomialNB()

In [69]:
model.fit(X_train, y_train)

MultinomialNB()

In [70]:
y_pred = model.predict(X_test)

In [71]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

In [72]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Prediction:", precision_score(y_test, y_pred))
print("Recall :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))

Accuracy: 0.9729206963249516
Prediction: 0.9915966386554622
Recall : 0.8137931034482758
F1 Score : 0.8939393939393939

In [73]:
X.shape

(5169, 3000)

In [74]:
y_pred = model.predict(X_test)

In [76]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

print("Accuracy: ", accuracy_score(y_test, y_pred))
print("Precision: ", precision_score(y_test, y_pred))
print("Recall :", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))

Accuracy:  0.9729206963249516
Precision:  0.9915966386554622
Recall : 0.8137931034482758
F1 Score: 0.8939393939393939

In [77]:
import joblib

joblib.dump(tfidf, "../models/vectorizer.pkl")
joblib.dump(model, "../models/model.pkl")

['../models/model.pkl']

In [79]:
import os
os.listdir("../models")

['model.pkl', 'vectorizer.pkl']

In [80]:
def predict_spam(text):
    transformed = transform_text(text)
    vectore_input = tfidf.transform([transformed])
    prediction = model.predict(vectore_input)[0]
    if prediction == 1:
        return "SPAM"
    else:
        return "HAM"

In [81]:
predict_spam("Congratulations! You have won a free iPhone. Click here now!")

'SPAM'

In [82]:
predict_spam("Hey Khushi!, are you free for class tomorrow?")

'HAM'